sonar.projectKey=project-2
sonar.projectName=project_2

sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.scm.provider=git

sonar.sources=library, repository, service, Client.py, container.py
sonar.sourceEncoding=UTF-8
sonar.language=py

sonar.python.coverage.reportPaths=coverage.xml
sonar.token=sqp_b71bf7ea438d15b49d3b299ba5a6f8db6bb2d18c

sonar.python.version=3.12.6

sonar.tests=Tests
